apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: install-chaincode
spec:
  params:
    - name: package-name
      type: string
  steps:
    - name: install-chaincode
      command:
        - /bin/bash
        - "-c"
      args: 
        - >-
          VERSION=$(awk '/version: /{print $NF}' ./gitops/$(params.package-name)/requirements.yaml)

          echo "Installing version $VERSION"

          ANSIBLE_COLLECTIONS_PATH=/root/.ansible/collections ansible-playbook ./packages/playbooks/install.yaml -e "package_name=$(params.package-name) package_version=$VERSION"
      image: image-registry.openshift-image-registry.svc:5000/ajman-dev/install-instantiate-chaincode
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - name: peers-config
          mountPath: /peers-config
        - name: land-admin-identity
          mountPath: /land-admin-identity
        - name: muni-admin-identity
          mountPath: /muni-admin-identity
      workingDir: $(workspaces.output.path)
  volumes:
    - name: peers-config
      configMap:
        name: peers-config
    - name: land-admin-identity
      secret:
        secretName: land-admin-identity 
    - name: muni-admin-identity
      secret:
        secretName: muni-admin-identity 
  workspaces:
    - name: output
